language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

services:
  - docker

script:
  - docker pull confluentinc/cp-zookeeper:5.5.1
  - docker pull confluentinc/cp-server:5.5.1
  - docker pull confluentinc/cp-schema-registry:5.5.1
  - cd cmd/integrationTests
  - docker-compose up -d
  - go test
  - cd ../internals
  - go test
  - sonar-scanner

addons:
  sonarcloud:
    organization: "abraham-leal"