language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

services:
  - docker

script:
  - cd cmd/integrationTests
  - go test
  - cd ../internals
  - go test
  - sonar-scanner

addons:
  sonarcloud:
    organization: "abraham-leal"