---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION}
    hostname: zookeeper
    container_name: zookeeper-testcontainers
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:${CONFLUENT_VERSION}
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry-src:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION}
    hostname: schema-registry-src
    container_name: schema-registry-testcontainers-src
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    volumes:
      - "./testingBasicAuth:/testing"
    environment:
      SCHEMA_REGISTRY_CONFLUENT_LICENSE: ""
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-src
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: schema-src
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_AUTHENTICATION_METHOD: "BASIC"
      SCHEMA_REGISTRY_AUTHENTICATION_ROLES: "onerole"
      SCHEMA_REGISTRY_AUTHENTICATION_REALM: "test"
      SCHEMA_REGISTRY_OPTS: "-Djava.security.auth.login.config=/testing/jaas"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "_schemas"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_MODE_MUTABILITY: "true"

  schema-registry-dst:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION}
    hostname: schema-registry-dst
    container_name: schema-registry-testcontainers-dst
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8082:8082"
    volumes:
      - "./testingBasicAuth:/testing"
    environment:
      SCHEMA_REGISTRY_CONFLUENT_LICENSE: ""
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-dst
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: schema-dst
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8082"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_AUTHENTICATION_METHOD: "BASIC"
      SCHEMA_REGISTRY_AUTHENTICATION_ROLES: "onerole"
      SCHEMA_REGISTRY_AUTHENTICATION_REALM: "test"
      SCHEMA_REGISTRY_OPTS: "-Djava.security.auth.login.config=/testing/jaas"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "_schemas-dst"
      SCHEMA_REGISTRY_MODE_MUTABILITY: "true"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
